---
# tasks file for docker-install
- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: present
    update_cache: true

- name: Install required system packages
  ansible.builtin.apt:
    name: "{{ apt_list }}"
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_key_link }}"
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb {{ docker_repository_link }} focal stable"
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Install Docker Compose
  ansible.builtin.pip:
    name: docker-compose==1.29.2
    state: present
