---
# vars file for docker-service

docker_service__compose:
  version: "3"
  services:
    app:
      image: antonaleks/101-todo-app
      restart: on-failure
      ports:
        - "80:80"
      environment:
        MYSQL_HOST: "{{ db_address }}"
        MYSQL_USER: root
        MYSQL_PASSWORD: "{{ db_password }}"
        MYSQL_DB: "{{ db_name }}"
